version: '3.8'
services:
  demo-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/users"]
      interval: 10s
      timeout: 5s
      retries: 5
