name: Aggregate Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  # Call unit test workflow
  unit-tests:
    uses: ./.github/workflows/unit.yml

  # Call integration test workflow (depends on unit tests)
  integration-tests:
    needs: unit-tests
    uses: ./.github/workflows/integration.yml

  # Call API test workflow (depends on integration tests)
  api-tests:
    needs: integration-tests
    uses: ./.github/workflows/api.yml
