name: API Isolated Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Run API isolated tests
      run: ./gradlew apiIsolatedTests
      
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: api-test-results
        path: "**/build/test-results/apiIsolatedTests/*.xml"
        retention-days: 5
