name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Run integration tests
      run: ./gradlew integrationTests
      
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: integration-test-results
        path: "**/build/test-results/integrationTests/*.xml"
        retention-days: 5
