name: Build & Unit Tests

on:
  workflow_dispatch:
  # Additional triggers can be uncommented as needed
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  unit:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      # Setup Java - adjust version as needed for your project
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          
      - name: Build & Run Unit Tests
        run: ./gradlew clean build
        
      # Equivalent to Jenkins junit step
      - name: Publish Test Results
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/test/*.xml'
          fail_on_failure: false