name: Build & Unit Tests

on:
  workflow_call:  # This workflow can be called by other workflows
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Using a reasonable default - adjust as needed
        distribution: 'temurin'
        
    - name: Build & Run Unit Tests
      run: ./gradlew clean build
      
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()  # Run this step even if the previous step fails
      with:
        files: '**/build/test-results/test/*.xml'
